services:
  m3u:
    image: m3u:latest   # use locally built image
    container_name: m3u
    build: .
    ports:
      - "9000:9000"
    command: ["python", "main.py"]
    restart: unless-stopped
    volumes:
      - '/data/media:/pi'